.dashAladinLite_js_metadata <- function() {
deps_metadata <- list(`dash_aladin_lite` = structure(list(name = "dash_aladin_lite",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'third_party/jquery-1.10.1.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashAladinLite",
all_files = FALSE), class = "html_dependency"),
`dash_aladin_lite` = structure(list(name = "dash_aladin_lite",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'third_party/aladin.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashAladinLite",
all_files = FALSE), class = "html_dependency"),
`dash_aladin_lite` = structure(list(name = "dash_aladin_lite",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_aladin_lite.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashAladinLite",
all_files = FALSE), class = "html_dependency"),
`dash_aladin_lite` = structure(list(name = "dash_aladin_lite",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_aladin_lite.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashAladinLite",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_aladin_lite` = structure(list(name = "dash_aladin_lite",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'third_party/aladin.min.css', head = NULL, attachment = NULL, package = "dashAladinLite",
all_files = FALSE), class = "html_dependency"))
return(deps_metadata)
}
